"""
app.py — Main Streamlit Dashboard
Reads pre-computed CSVs generated by update_data.py.
Also has a built-in "Run Update Now" button for first-time setup.
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
import yfinance as yf
import os, sys
from datetime import datetime, timedelta

st.set_page_config(
    page_title="AI Stock Predictor 🇮🇳",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown("""
<style>
div[data-testid="metric-container"] {
    background: #f8f9fa;
    border-radius: 10px;
    padding: 10px;
    border: 1px solid #e0e0e0;
}
</style>
""", unsafe_allow_html=True)

# ── Add project root to path so imports work on Streamlit Cloud ──
sys.path.append(os.path.dirname(os.path.abspath(__file__)))


# ─────────────────────────────────────────────────────────────
# DATA LOADERS
# ─────────────────────────────────────────────────────────────

@st.cache_data(ttl=3600)
def load_predictions():
    path = os.path.join("predictions", "latest_predictions.csv")
    if not os.path.exists(path):
        return pd.DataFrame()
    return pd.read_csv(path)

@st.cache_data(ttl=3600)
def load_market_sentiment():
    path = os.path.join("predictions", "market_sentiment.csv")
    if not os.path.exists(path):
        return {}
    return pd.read_csv(path).iloc[0].to_dict()

@st.cache_data(ttl=1800)
def load_price_chart(symbol: str):
    try:
        df = yf.download(symbol, period="6mo", progress=False, auto_adjust=True)
        df.columns = [c.lower() for c in df.columns]
        return df
    except:
        return pd.DataFrame()


# ─────────────────────────────────────────────────────────────
# BUILT-IN UPDATE RUNNER  (so Streamlit Cloud can self-update)
# ─────────────────────────────────────────────────────────────

def run_update_in_app(quick_mode: bool = False):
    """
    Runs the full data pipeline inside the Streamlit app itself.
    quick_mode = True → only first 20 NSE stocks + 5 crypto (faster for testing)
    """
    from config import NSE_STOCKS, CRYPTO_SYMBOLS, DATA_DIR
    from data.fetch_stocks  import fetch_all_stocks
    from data.fetch_news    import fetch_all_news
    from sentiment.analyzer import compute_stock_sentiment, compute_market_sentiment
    from model.predictor    import run_predictions

    today = datetime.now().strftime("%Y-%m-%d")

    if quick_mode:
        nse_list    = NSE_STOCKS[:20]
        crypto_list = CRYPTO_SYMBOLS[:5]
        st.info("⚡ Quick mode: processing 20 NSE + 5 crypto stocks for speed.")
    else:
        nse_list    = NSE_STOCKS
        crypto_list = CRYPTO_SYMBOLS

    progress = st.progress(0, text="Starting...")
    status   = st.empty()

    # Step 1
    status.write("**Step 1/4** — Downloading stock price data from Yahoo Finance...")
    progress.progress(10, text="Fetching NSE stocks...")
    nse_data = fetch_all_stocks(nse_list, label="NSE")

    progress.progress(25, text="Fetching crypto...")
    crypto_data = fetch_all_stocks(crypto_list, label="Crypto")
    all_data = {**nse_data, **crypto_data}

    if not all_data:
        st.error("❌ Could not download any stock data. Check your internet connection.")
        return False

    # Step 2
    status.write("**Step 2/4** — Fetching news from RSS feeds + NewsAPI...")
    progress.progress(40, text="Fetching news...")
    news_df = fetch_all_news()

    # Step 3
    status.write("**Step 3/4** — Analysing news sentiment...")
    progress.progress(60, text="Running sentiment analysis...")
    if not news_df.empty:
        sentiment_df = compute_stock_sentiment(news_df)
        market_sent  = compute_market_sentiment(news_df)
    else:
        sentiment_df = pd.DataFrame()
        market_sent  = {"score": 0.0, "label": "Neutral ⚪", "total_articles": 0}

    # Step 4
    status.write("**Step 4/4** — Training ML models and generating predictions...")
    progress.progress(75, text="Training models (this takes a few minutes)...")
    predictions_df = run_predictions(all_data, sentiment_df)

    if predictions_df.empty:
        st.error("❌ Predictions failed. Please try again.")
        return False

    # Tag market type
    nse_set    = set(NSE_STOCKS)
    crypto_set = set(CRYPTO_SYMBOLS)
    predictions_df["market"] = predictions_df["symbol"].apply(
        lambda s: "NSE" if s in nse_set else ("Crypto" if s in crypto_set else "Other")
    )
    predictions_df["date"] = today

    # Save
    os.makedirs(DATA_DIR, exist_ok=True)
    os.makedirs(os.path.join(DATA_DIR, "history"), exist_ok=True)

    predictions_df.to_csv(os.path.join(DATA_DIR, "latest_predictions.csv"), index=False)
    predictions_df.to_csv(os.path.join(DATA_DIR, "history", f"{today}.csv"), index=False)
    market_sent["date"] = today
    pd.DataFrame([market_sent]).to_csv(os.path.join(DATA_DIR, "market_sentiment.csv"), index=False)

    progress.progress(100, text="Done!")
    status.empty()
    return True


# ─────────────────────────────────────────────────────────────
# MAIN APP
# ─────────────────────────────────────────────────────────────

def main():
    st.markdown("# 📈 AI Stock Predictor — India & Crypto")
    st.markdown("##### Powered by Machine Learning + News Sentiment | Updates Every Morning 🌅")
    st.divider()

    df          = load_predictions()
    market_sent = load_market_sentiment()

    # ── NO DATA STATE ─────────────────────────────────────────
    if df.empty:
        st.warning("### ⚠️ No prediction data found yet.")
        st.markdown("This is normal on first launch. Click the button below to generate your first predictions.")

        col1, col2 = st.columns(2)
        with col1:
            st.markdown("#### ⚡ Quick Start (recommended first time)")
            st.markdown("Runs on **20 NSE + 5 crypto** stocks — takes about **5–8 minutes**")
            if st.button("▶ Run Quick Update", type="primary", use_container_width=True):
                with st.spinner("Running... do not close this tab."):
                    success = run_update_in_app(quick_mode=True)
                if success:
                    st.success("✅ Done! Refreshing dashboard...")
                    st.cache_data.clear()
                    st.rerun()

        with col2:
            st.markdown("#### 🔄 Full Update")
            st.markdown("Runs on **all 200+ NSE + 10 crypto** stocks — takes about **25–35 minutes**")
            if st.button("▶ Run Full Update", use_container_width=True):
                with st.spinner("Running full update... do not close this tab."):
                    success = run_update_in_app(quick_mode=False)
                if success:
                    st.success("✅ Done! Refreshing dashboard...")
                    st.cache_data.clear()
                    st.rerun()

        st.divider()
        st.info("""
        **After the first run**, this app auto-updates every weekday at **6:30 AM IST** via GitHub Actions.
        You never need to click this button again — it's only for the very first time.
        """)
        return

    # ── HEADER METRICS ────────────────────────────────────────
    updated_at = df["updated_at"].iloc[0] if "updated_at" in df.columns else "—"
    total   = len(df)
    buy_ct  = (df["signal"].str.startswith("BUY")).sum()
    sell_ct = (df["signal"].str.startswith("SELL")).sum()
    hold_ct = (df["signal"].str.startswith("HOLD")).sum()
    sent_score = market_sent.get("score", 0)
    sent_label = market_sent.get("label", "Neutral ⚪")

    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("🕐 Last Updated",  updated_at.split(" ")[0] if updated_at != "—" else "—")
    c2.metric("🟢 BUY Signals",   buy_ct,  f"{buy_ct/total*100:.0f}% of stocks")
    c3.metric("🔴 SELL Signals",  sell_ct, f"{sell_ct/total*100:.0f}% of stocks")
    c4.metric("🟡 HOLD Signals",  hold_ct, f"{hold_ct/total*100:.0f}% of stocks")
    c5.metric("📰 Market Mood",   sent_label, f"Score: {sent_score:+.2f}")

    st.divider()

    # ── SIDEBAR ───────────────────────────────────────────────
    with st.sidebar:
        st.markdown("## ⚙️ Filters")
        signal_filter = st.multiselect(
            "Signal",
            ["BUY 🟢", "SELL 🔴", "HOLD 🟡"],
            default=["BUY 🟢", "SELL 🔴", "HOLD 🟡"],
        )
        conf_min = st.slider("Min Confidence %", 50, 95, 50)
        sort_by  = st.selectbox("Sort by", ["confidence", "prob_up", "sentiment_score", "symbol"])

        st.divider()
        st.markdown("### 🔄 Manual Refresh")
        st.markdown("Force re-run the full pipeline right now:")
        if st.button("▶ Run Update Now", use_container_width=True):
            with st.spinner("Updating... do not close tab."):
                success = run_update_in_app(quick_mode=False)
            if success:
                st.success("Done!")
                st.cache_data.clear()
                st.rerun()

        st.divider()
        st.markdown("### 📌 Quick Lookup")
        lookup = st.text_input("Symbol (e.g. RELIANCE.NS)", "")
        if lookup:
            row = df[df["symbol"] == lookup.strip().upper()]
            if row.empty:
                st.error("Not found")
            else:
                r = row.iloc[0]
                st.markdown(f"**{r['symbol']}**")
                st.markdown(f"Signal: {r.get('signal','—')}")
                st.markdown(f"Confidence: {r.get('confidence',0):.1f}%")
                st.markdown(f"Last Close: ₹{r.get('last_close',0):.2f}")
                st.markdown(f"Sentiment: {r.get('sentiment_label','—')}")

    # ── TABS ──────────────────────────────────────────────────
    tab1, tab2, tab3, tab4 = st.tabs([
        "🏦 NSE Stocks", "₿ Crypto", "📰 News Sentiment", "📊 Signal Summary"
    ])

    # ─ TAB 1: NSE ─────────────────────────────────────────────
    with tab1:
        nse_df = df[df["market"] == "NSE"].copy() if "market" in df.columns else df.copy()
        mask   = nse_df["signal"].isin(signal_filter) & (nse_df["confidence"] >= conf_min)
        filt   = nse_df[mask].sort_values(sort_by, ascending=False)

        st.markdown(f"### 🏦 NSE Stocks — {len(filt)} results")

        col_pie, col_hist = st.columns([1, 3])
        with col_pie:
            pie = px.pie(
                values=[
                    (nse_df["signal"].str.startswith("BUY")).sum(),
                    (nse_df["signal"].str.startswith("SELL")).sum(),
                    (nse_df["signal"].str.startswith("HOLD")).sum(),
                ],
                names=["BUY 🟢", "SELL 🔴", "HOLD 🟡"],
                color_discrete_sequence=["#00e676", "#ff5252", "#ffd740"],
                hole=0.55,
            )
            pie.update_layout(height=200, margin=dict(t=10,b=10,l=0,r=0), showlegend=False,
                              paper_bgcolor="rgba(0,0,0,0)")
            st.plotly_chart(pie, use_container_width=True)

        with col_hist:
            fig_h = px.histogram(nse_df, x="confidence", nbins=20,
                                  color_discrete_sequence=["#1f77b4"],
                                  title="Confidence distribution")
            fig_h.update_layout(height=200, margin=dict(t=30,b=10,l=10,r=10),
                                paper_bgcolor="rgba(0,0,0,0)")
            st.plotly_chart(fig_h, use_container_width=True)

        show_cols = ["symbol","signal","confidence","direction","last_close",
                     "est_price_low","est_price_high","rsi","sentiment_label"]
        display   = [c for c in show_cols if c in filt.columns]
        st.dataframe(
            filt[display].reset_index(drop=True),
            use_container_width=True, height=420,
            column_config={
                "confidence":     st.column_config.ProgressColumn("Confidence %", min_value=0, max_value=100),
                "last_close":     st.column_config.NumberColumn("Last Close ₹", format="₹%.2f"),
                "est_price_low":  st.column_config.NumberColumn("Est. Low ₹",   format="₹%.2f"),
                "est_price_high": st.column_config.NumberColumn("Est. High ₹",  format="₹%.2f"),
                "rsi":            st.column_config.NumberColumn("RSI",           format="%.1f"),
            },
        )

        st.divider()
        st.markdown("### 🔍 Stock Deep Dive")
        sel = st.selectbox("Select stock", sorted(nse_df["symbol"].tolist()), key="nse_sel")
        if sel:
            render_stock_detail(df, sel, currency="₹")

    # ─ TAB 2: CRYPTO ──────────────────────────────────────────
    with tab2:
        cdf = df[df["market"] == "Crypto"].copy() if "market" in df.columns else pd.DataFrame()
        if cdf.empty:
            st.info("No crypto data yet — run a Full Update.")
        else:
            mask_c = cdf["signal"].isin(signal_filter) & (cdf["confidence"] >= conf_min)
            filt_c = cdf[mask_c].sort_values(sort_by, ascending=False)
            st.markdown(f"### ₿ Crypto — {len(filt_c)} results")
            display_c = [c for c in ["symbol","signal","confidence","direction",
                                      "last_close","est_price_low","est_price_high",
                                      "rsi","sentiment_label"] if c in filt_c.columns]
            st.dataframe(
                filt_c[display_c].reset_index(drop=True),
                use_container_width=True, height=360,
                column_config={
                    "confidence":     st.column_config.ProgressColumn("Confidence %", min_value=0, max_value=100),
                    "last_close":     st.column_config.NumberColumn("Last Price $", format="$%.2f"),
                    "est_price_low":  st.column_config.NumberColumn("Est. Low $",   format="$%.2f"),
                    "est_price_high": st.column_config.NumberColumn("Est. High $",  format="$%.2f"),
                },
            )
            st.divider()
            st.markdown("### 🔍 Crypto Deep Dive")
            sel_c = st.selectbox("Select crypto", sorted(cdf["symbol"].tolist()), key="crypto_sel")
            if sel_c:
                render_stock_detail(df, sel_c, currency="$")

    # ─ TAB 3: NEWS SENTIMENT ─────────────────────────────────
    with tab3:
        st.markdown("### 📰 News Sentiment by Stock")
        if "sentiment_score" not in df.columns:
            st.info("No sentiment data yet.")
        else:
            top40 = df.nlargest(40, "article_count") if "article_count" in df.columns else df.head(40)
            fig_bar = px.bar(
                top40.sort_values("sentiment_score", ascending=True),
                x="sentiment_score", y="symbol", orientation="h",
                color="sentiment_score",
                color_continuous_scale=["#ff5252","#ffd740","#00e676"],
                color_continuous_midpoint=0,
                title="Sentiment score (top 40 most-mentioned stocks)",
            )
            fig_bar.update_layout(height=580, margin=dict(l=120,r=20,t=50,b=20),
                                   paper_bgcolor="rgba(0,0,0,0)", coloraxis_showscale=False)
            st.plotly_chart(fig_bar, use_container_width=True)

            if "top_headline" in df.columns and "article_count" in df.columns:
                st.markdown("### 📋 Top Headlines")
                hl = df[df["article_count"] > 0][
                    ["symbol","sentiment_label","article_count","top_headline"]
                ].sort_values("article_count", ascending=False).head(30)
                st.dataframe(hl.reset_index(drop=True), use_container_width=True, height=380)

    # ─ TAB 4: SIGNAL SUMMARY ─────────────────────────────────
    with tab4:
        st.markdown("### 📊 Signal Summary")
        c_buy, c_sell = st.columns(2)

        with c_buy:
            st.markdown("#### 🟢 Top BUY Picks")
            bdf = df[df["signal"].str.startswith("BUY")].sort_values(
                "confidence", ascending=False
            ).head(15)[["symbol","confidence","prob_up","sentiment_label","last_close"]]
            st.dataframe(bdf.reset_index(drop=True), use_container_width=True,
                         column_config={"confidence": st.column_config.ProgressColumn(
                             "Confidence %", min_value=0, max_value=100)})

        with c_sell:
            st.markdown("#### 🔴 Top SELL Picks")
            sdf = df[df["signal"].str.startswith("SELL")].sort_values(
                "confidence", ascending=False
            ).head(15)[["symbol","confidence","prob_down","sentiment_label","last_close"]]
            st.dataframe(sdf.reset_index(drop=True), use_container_width=True,
                         column_config={"confidence": st.column_config.ProgressColumn(
                             "Confidence %", min_value=0, max_value=100)})

        if "model_accuracy" in df.columns:
            st.divider()
            st.markdown("#### 🎯 Model Accuracy Distribution")
            fig_acc = px.histogram(df, x="model_accuracy", nbins=20,
                                    color_discrete_sequence=["#7c4dff"],
                                    title="Cross-validation accuracy across all models")
            fig_acc.update_layout(paper_bgcolor="rgba(0,0,0,0)", height=300)
            st.plotly_chart(fig_acc, use_container_width=True)
            st.info(f"Average model accuracy: **{df['model_accuracy'].mean():.1f}%**")

    st.divider()
    st.caption("⚠️ Educational purposes only. Not financial advice. Always do your own research.")


# ─────────────────────────────────────────────────────────────
# STOCK DETAIL CARD
# ─────────────────────────────────────────────────────────────

def render_stock_detail(df, symbol, currency="₹"):
    row = df[df["symbol"] == symbol]
    if row.empty:
        st.warning(f"No data for {symbol}")
        return
    r = row.iloc[0]

    c1, c2, c3 = st.columns(3)
    with c1:
        st.markdown(f"**Signal:** {r.get('signal','—')}")
        st.markdown(f"**Direction:** {r.get('direction','—')}")
        st.markdown(f"**Confidence:** {r.get('confidence',0):.1f}%")
        st.markdown(f"**Last Close:** {currency}{r.get('last_close',0):.2f}")
        st.markdown(f"**Est. Range:** {currency}{r.get('est_price_low',0):.2f} – {currency}{r.get('est_price_high',0):.2f}")

    with c2:
        rsi = r.get("rsi", 50) or 50
        st.markdown(f"**RSI (14):** {rsi:.1f}")
        if rsi > 70:   st.warning("⚠️ RSI > 70 — Overbought")
        elif rsi < 30: st.success("✅ RSI < 30 — Oversold")
        else:          st.info(f"RSI neutral ({rsi:.0f})")
        st.markdown(f"**MACD:** {r.get('macd','—')}")
        st.markdown(f"**Volume Ratio:** {r.get('volume_ratio','—')}")

    with c3:
        st.markdown(f"**Sentiment:** {r.get('sentiment_label','—')}")
        st.markdown(f"**Score:** {r.get('sentiment_score',0):+.3f}")
        st.markdown(f"**Articles:** {r.get('article_count',0)}")
        hl = r.get("top_headline","")
        if hl:
            st.markdown(f"**Headline:** _{str(hl)[:100]}..._")

    st.markdown(f"#### {symbol} — 6-Month Price Chart")
    chart_df = load_price_chart(symbol)
    if not chart_df.empty and all(c in chart_df.columns for c in ["open","high","low","close"]):
        chart_df["sma20"] = chart_df["close"].rolling(20).mean()
        chart_df["sma50"] = chart_df["close"].rolling(50).mean()
        fig = go.Figure()
        fig.add_trace(go.Candlestick(
            x=chart_df.index,
            open=chart_df["open"], high=chart_df["high"],
            low=chart_df["low"],   close=chart_df["close"],
            name="OHLC",
            increasing_line_color="#00e676", decreasing_line_color="#ff5252",
        ))
        fig.add_trace(go.Scatter(x=chart_df.index, y=chart_df["sma20"],
                                  line=dict(color="#ffd740", width=1), name="SMA 20"))
        fig.add_trace(go.Scatter(x=chart_df.index, y=chart_df["sma50"],
                                  line=dict(color="#00d4ff", width=1), name="SMA 50"))
        fig.add_hrect(
            y0=r.get("est_price_low",0), y1=r.get("est_price_high",0),
            fillcolor="rgba(124,77,255,0.15)", line_width=0,
            annotation_text="Predicted Range", annotation_position="top right",
        )
        fig.update_layout(
            height=400, xaxis_rangeslider_visible=False,
            paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
            margin=dict(l=10,r=10,t=20,b=10),
        )
        fig.update_xaxes(showgrid=False)
        fig.update_yaxes(showgrid=True, gridcolor="rgba(200,200,200,0.2)")
        st.plotly_chart(fig, use_container_width=True)
    else:
        st.info("Chart data unavailable.")


if __name__ == "__main__":
    main()
